#+AUTHOR: Alyaman Maasarani
#+EMAIL: ahm363@student.bau.edu.lb
#+TITLE: Experiment 3 Report (Qualitative Analysis of Cations)
  
* Purpose
  The purpose of this experiment is to learn how to detect the presence/absence of certain cations through their reactions with certain substances. At the end, the student is able to detect $Ag^{+}$, $Ba^{2+}$ and $Fe^{3+}$. Additionally, we also learn how to properly separate precipitate from liquid, how to filter a liquid, and how to clean glassware.

* Scheme
  /insert scheme here/

* Conclusion
  We conclude that $Ag^+$ turns into a white precipitate with $HCl$, and returns into a precipitate after adding $NH_3$ and $HNO_3$ with release of heat as a sign. $Fe^{3+}$ reacts with $NH_3$ and turns a red precipitate scattered around the tube, and can further turn into a red or dark blue solution if we add $KSCN$ or $NH_3 + K_4[Fe(CN)_6]$ respectively. $Ba^{2+}$ turns into a precipitate with a light yellow solution upon addition of $K_2CrO_4$. These reactions allow us to detect the presence of $Ag^+$, $Fe^{3+}$ and $Ba^{2+}$.
  

  # todo: add hcl to scheme fe3+
